services:
  app:
    container_name: app-${PROJECT_NAME}
    build:
      context: ./
      dockerfile: ${PATH_TO_DOCKERFILE}
    volumes:
      - ./app:/app:rw
      - ./frontend/build:/var/www/shared/build:rw
      - ./docker/web/php.ini:/etc/php/8.0/fpm/conf.d/90-php.ini
      - ./docker/web/php.ini:/etc/php/8.0/cli/conf.d/90-php.ini
      - ./docker/web/logs/php:/var/log/php/:rw
      - ./docker/web/logs/nginx:/var/log/nginx/:rw
      - ./docker/web/logs/supervisor:/var/log/supervisor/:rw
      - ./docker/web/nginx.conf:/etc/nginx/sites-available/default
    environment:
      TZ: ${PHP_DATE_TIMEZONE}
      PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
      PHP_POST_MAX_SIZE: ${PHP_POST_MAX_SIZE}
      PHP_MAX_FILE_UPLOADS: ${PHP_MAX_FILE_UPLOADS}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}
      PHP_MAX_EXECUTION_TIME: ${PHP_MAX_EXECUTION_TIME}
      ERROR_REPORTING: ${ERROR_REPORTING}
      PHP_DATE_TIMEZONE: ${PHP_DATE_TIMEZONE}
      PHP_LOG_ERRORS: ${PHP_LOG_ERRORS}
      PHP_LOG_ERRORS_MAX_LEN: ${PHP_LOG_ERRORS_MAX_LEN}
      OPCACHE_ENABLE: ${OPCACHE_ENABLE}
      OPCACHE_REVALIDATE_FREQ: ${OPCACHE_REVALIDATE_FREQ}
      OPCACHE_ENABLE_CLI: ${OPCACHE_ENABLE_CLI}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${NGINX_LOCAL_PORT}:80
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  mysql:
    image: mysql:9.2.0
    container_name: mysql-${PROJECT_NAME}
    environment:
      TZ: ${PHP_DATE_TIMEZONE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
    volumes:
      - ./docker/database/mysql:/var/lib/mysql
      - ./docker/database/my.cnf:/etc/mysql/conf.d/my.cnf
    healthcheck:
      test: ["CMD", "mysql", "-u${MYSQL_USER}", "-p${MYSQL_PASSWORD}", "-e", "use ${MYSQL_DATABASE}; show tables;"]
      interval: 5s
      retries: 50

  redis:
    image: redis:6.2.5-alpine
    volumes:
      - ./docker/database/redis:/data
    depends_on:
      mysql:
        condition: service_healthy

  phpmyadmin:
    container_name: pma-${PROJECT_NAME}
    image: phpmyadmin
    ports:
      - ${PMA_PORT}:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      mysql:
        condition: service_healthy
